
global:
  openshiftGitopsNamespace: openshift-gitops

applications:
  ##  Applications in platform-admin namespace
  - appName: networking
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: main
    argocdNamespace: platform-admin
    applicationProject: networking
    applicationNamespace: networking
  - appName: devops
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: main
    argocdNamespace: platform-admin
    applicationProject: devops
    applicationNamespace: devops
  - appName: operators
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: main
    argocdNamespace: platform-admin
    applicationProject: operators
    applicationNamespace: operators
  - appName: security
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: main
    argocdNamespace: platform-admin
    applicationProject: security
    applicationNamespace: security

  ##  Applications in application namespace
  - appName: pipeline-prod-frontend
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    imageName: quay.io/fanyaegb/pipeline-vote-ui:prod
    branch: main
    argocdNamespace: tenant-apps
    applicationProject: prod
  - appName: pipeline-prod-backend 
    remoteAppNamespace: tenant-apps
    imageName: quay.io/fanyaegb/pipeline-vote-api:prod
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: main
    argocdNamespace: tenant-apps
    applicationProject: prod
  - appName: pipeline-dev-frontend    
    remoteAppNamespace: tenant-apps
    imageName: quay.io/fanyaegb/pipeline-vote-ui:dev
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: dev
    argocdNamespace: tenant-apps
    applicationProject: dev
  - appName: pipeline-dev-backend
    remoteAppNamespace: tenant-apps
    imageName: quay.io/fanyaegb/pipeline-vote-api:dev
    repoUrl: git@github.com:rh-fran6/pipelines-demo.git
    branch: dev
    argocdNamespace: tenant-apps
    applicationProject: dev

